import type { ImageAsset } from '@/types';

// The asset manifest (build spec Section 9.3–9.4). Every image on the site is
// registered here. `src: null` renders the local Placeholder component. When a
// real file lands in /public/images, set `src` and the placeholder disappears
// with no component changes. Alt text lives here, not inline, so it can be
// reviewed as a set (Section 9.6).

export const IMAGE_MANIFEST: ImageAsset[] = [
  // --- Hero -----------------------------------------------------------------
  {
    id: 'hero-primary',
    src: null,
    alt: 'A dark navy wool baggy cricket cap with an embroidered club crest, held against a weathered pavilion wall.',
    subject:
      'A single navy baggy cap held in one hand against a pavilion wall, or worn, shot from just below eye level.',
    crop: 'In the instant frame, right column of the hero. Crop tight enough that the crest is legible.',
    treatment: 'Warm light, hard shadow.',
    aspectDesktop: '4:3',
    aspectMobile: '4:5',
    width: 1600,
    height: 1200,
    decorative: false,
    priority: true,
  },
  {
    id: 'hero-detail',
    src: null,
    alt: 'Close-up of gold embroidered thread forming a club crest on wool.',
    subject: 'Macro of embroidery on the hero cap.',
    crop: 'Square, offset over the hero base image on desktop only.',
    treatment: 'Macro detail, quality 90.',
    aspectDesktop: '1:1',
    aspectMobile: 'hidden',
    width: 720,
    height: 720,
    decorative: false,
  },
  // --- Headwear categories --------------------------------------------------
  {
    id: 'category-baggy',
    src: null,
    alt: 'A traditional wool baggy cricket cap in club colours.',
    subject: 'Wool baggy cap, studio still life on cream paper, raking light.',
    crop: 'Vertical, product centred with generous headroom.',
    treatment: 'Studio still life.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  {
    id: 'category-sunhat',
    src: null,
    alt: 'A wide-brim cricket sun hat with an embroidered club badge on the front.',
    subject: 'Wide-brim sun hat photographed from slightly below, brim filling the upper frame.',
    crop: 'Vertical, brim shape emphasised.',
    treatment: 'Studio still life.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  {
    id: 'category-performance',
    src: null,
    alt: 'A lightweight performance cricket cap in club colours.',
    subject: 'Lightweight performance cap, three-quarter view, backlit to show fabric.',
    crop: 'Vertical, cooler light than the other two.',
    treatment: 'Backlit, cooler grade.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  // --- Editorial ------------------------------------------------------------
  {
    id: 'statement-ground',
    src: null,
    alt: 'An empty village cricket ground in late afternoon light.',
    subject: 'Empty club ground in late afternoon light, sightscreen and pavilion visible, no people.',
    crop: 'Full bleed, letterboxed on desktop.',
    treatment: 'Warm, slightly desaturated, deep blacks.',
    aspectDesktop: '21:9',
    aspectMobile: '3:2',
    width: 2100,
    height: 900,
    decorative: false,
  },
  {
    id: 'occasions-honours',
    src: null,
    alt: 'A painted honours board listing club captains inside a cricket pavilion.',
    subject: 'Honours board or club roll of names in a pavilion.',
    crop: 'Overlaps the grid on desktop, placed after row two on mobile.',
    treatment: 'Ambient, slightly underexposed, warm.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  // --- Product --------------------------------------------------------------
  {
    id: 'product-construction',
    src: null,
    alt: 'The inside of a cricket cap showing panel seams, lining and a woven label.',
    subject: 'Cap turned inside out or part-constructed showing panels, lining and internal label.',
    crop: 'Studio, high detail, neutral background. Runs slightly beyond the top of the text block.',
    treatment: 'Studio, high detail.',
    aspectDesktop: '4:5',
    aspectMobile: '3:2',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  {
    id: 'product-stack',
    src: null,
    alt: 'A stack of custom cricket caps in matching club colours.',
    subject: "Stack of six to eight caps in one club's colours.",
    crop: 'Studio, top light, tight crop. Crops off the right page edge on desktop.',
    treatment: 'Studio, top light.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  // --- Characters (illustration) -------------------------------------------
  {
    id: 'character-scene',
    src: null,
    alt: 'Illustration of Baggy and Brim side by side, one older cricketer in whites holding a scorebook, one relaxed figure under a wide-brim sun hat.',
    subject: 'Illustration. Baggy and Brim side by side, one holding a scorebook, one under a sun hat.',
    crop: 'Full bleed on cream, print texture visible.',
    treatment: 'Screen-print texture, ink plus one accent.',
    aspectDesktop: '16:9',
    aspectMobile: 'hidden',
    width: 1920,
    height: 1080,
    decorative: false,
  },
  {
    id: 'character-scene-mobile',
    src: null,
    alt: 'Illustration of Baggy and Brim, one older cricketer in whites holding a scorebook and one relaxed figure under a wide-brim sun hat.',
    subject: 'Mobile crop of the character scene centred on both figures.',
    crop: '4:5 composition centred on both figures.',
    treatment: 'Screen-print texture, ink plus one accent.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  // --- Process --------------------------------------------------------------
  {
    id: 'process-approval',
    src: null,
    alt: 'A printed cricket cap design marked up by hand with pencil notes.',
    subject: 'A cap design visual printed on paper on a table, marked up in pencil.',
    crop: 'Overhead, natural light. Breaks the sequence at half width, right aligned.',
    treatment: 'Natural light.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  // --- Volumes --------------------------------------------------------------
  {
    id: 'volumes-team',
    src: null,
    alt: 'Custom cricket caps laid out along a changing room bench.',
    subject: 'A row of caps laid out on a changing room bench.',
    crop: 'Inside the page container, single editorial image. Low contrast, ambient.',
    treatment: 'Low contrast, ambient.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  // --- Journal / social -----------------------------------------------------
  {
    id: 'journal-default',
    src: null,
    alt: 'A custom cricket cap photographed as a still life.',
    subject: 'Fallback featured image for Journal articles without art.',
    crop: 'Studio still life, neutral.',
    treatment: 'Studio still life.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'og-default',
    src: null,
    alt: '',
    subject: 'Social sharing image, wordmark on ink with a single cap.',
    crop: 'Composed for 1200x630.',
    treatment: 'Ink background.',
    aspectDesktop: '40:21',
    aspectMobile: '40:21',
    width: 1200,
    height: 630,
    decorative: true,
  },

  // --- Landing page: /custom-cricket-caps -----------------------------------
  {
    id: 'lp-hero-custom',
    src: null,
    alt: 'Three custom cricket caps, one baggy, one sun hat and one performance cap, arranged on cream paper and shot from above.',
    subject: 'A group of three caps, one of each style, arranged on cream paper, shot from above.',
    crop: 'Right-weighted, 3:2, not full bleed.',
    treatment: 'Studio still life on cream.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-custom-crest',
    src: null,
    alt: 'Macro of an embroidered club crest on the front panel of a cricket cap.',
    subject: 'Macro embroidery on a front panel.',
    crop: 'Macro, tight.',
    treatment: 'Macro detail, quality 90.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  {
    id: 'lp-custom-club',
    src: null,
    alt: 'A cricket club pavilion exterior in summer light.',
    subject: 'A club pavilion exterior in summer light.',
    crop: 'Ambient, wide.',
    treatment: 'Warm summer light.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },

  // --- Landing page: /baggy-cricket-caps ------------------------------------
  {
    id: 'lp-hero-baggy',
    src: null,
    alt: 'A single wool baggy cricket cap in club colours, three-quarter view, with the embroidered crest legible.',
    subject: 'Single baggy cap, three-quarter view, hard light, crest legible.',
    crop: 'Right-weighted, 3:2.',
    treatment: 'Hard light.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-baggy-inside',
    src: null,
    alt: 'The inside of a baggy cricket cap showing an internal woven label and an embroidered cap number.',
    subject: 'Cap turned to show the internal label and cap number.',
    crop: 'Studio, high detail.',
    treatment: 'Studio, high detail.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
  {
    id: 'lp-baggy-presentation',
    src: null,
    alt: 'A baggy cricket cap in a presentation box on a pavilion table.',
    subject: 'Cap in a presentation box on a pavilion table.',
    crop: 'Warm, ambient.',
    treatment: 'Warm low light.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },

  // --- Landing page: /cricket-sun-hats --------------------------------------
  {
    id: 'lp-hero-sunhat',
    src: null,
    alt: 'A custom cricket sun hat photographed from below against a bright sky, the wide brim dominating the frame.',
    subject: 'Sun hat photographed from below against a bright sky, brim shape dominant.',
    crop: 'Right-weighted, 3:2.',
    treatment: 'Bright, high key.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-sunhat-field',
    src: null,
    alt: 'A fielder in a club cricket sun hat standing at the boundary, shot from behind.',
    subject: 'A fielder in a club sun hat at the boundary, shot from behind, no face required.',
    crop: 'Wide, ambient.',
    treatment: 'Warm, ambient.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-sunhat-detail',
    src: null,
    alt: 'Macro of the brim edge stitching and embroidered crest on a cricket sun hat.',
    subject: 'Macro of the brim edge stitching and crest.',
    crop: 'Macro, tight.',
    treatment: 'Macro detail, quality 90.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },

  // --- Landing page: /performance-cricket-caps ------------------------------
  {
    id: 'lp-hero-performance',
    src: null,
    alt: 'A lightweight performance cricket cap in club colours, three-quarter view, backlit.',
    subject: 'Performance cap, three-quarter view, backlit, cooler light than the other pages.',
    crop: 'Right-weighted, 3:2.',
    treatment: 'Backlit, cooler grade.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-performance-training',
    src: null,
    alt: 'A performance cricket cap worn during a training session, shot in profile.',
    subject: 'Cap worn during a training session, shot from behind or in profile.',
    crop: 'Ambient, action-adjacent.',
    treatment: 'Cooler grade.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-performance-detail',
    src: null,
    alt: 'Macro of the peak edge and embroidered crest on a performance cricket cap.',
    subject: 'Macro of the peak edge and crest.',
    crop: 'Macro, tight.',
    treatment: 'Macro detail, quality 90.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },

  // --- Landing page: /cricket-presentation-caps -----------------------------
  {
    id: 'lp-hero-presentation',
    src: null,
    alt: 'A single presentation cricket cap on a pavilion table beside an honours board, in warm low light.',
    subject: 'A single cap on a pavilion table beside an honours board, warm low light.',
    crop: 'Right-weighted, 3:2.',
    treatment: 'Warm low light.',
    aspectDesktop: '3:2',
    aspectMobile: '4:5',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-presentation-box',
    src: null,
    alt: 'A presentation cricket cap in a box with a named card.',
    subject: 'Cap in a presentation box with a named card.',
    crop: 'Studio, warm.',
    treatment: 'Warm low light.',
    aspectDesktop: '3:2',
    aspectMobile: '3:2',
    width: 1500,
    height: 1000,
    decorative: false,
  },
  {
    id: 'lp-presentation-number',
    src: null,
    alt: 'Macro of an embroidered cap number inside a cricket cap.',
    subject: 'Macro of an embroidered cap number inside a cap.',
    crop: 'Macro, tight.',
    treatment: 'Macro detail, quality 90.',
    aspectDesktop: '4:5',
    aspectMobile: '4:5',
    width: 1280,
    height: 1600,
    decorative: false,
  },
];

const IMAGE_MAP: ReadonlyMap<string, ImageAsset> = new Map(
  IMAGE_MANIFEST.map((asset) => [asset.id, asset]),
);

/** Resolve a manifest entry by ID. Throws on an unknown ID so typos fail fast. */
export function getImageAsset(id: string): ImageAsset {
  const asset = IMAGE_MAP.get(id);
  if (!asset) {
    throw new Error(`Unknown image asset id: "${id}". Register it in image-manifest.ts.`);
  }
  return asset;
}

/** Manifest entries still awaiting a real file (used by scripts/check-images.ts). */
export function getUnfulfilledImages(): ImageAsset[] {
  return IMAGE_MANIFEST.filter((asset) => asset.src === null);
}
